--Hotel Database yaratmaq, dushunsek ki bu Database Reception/Manager'in hotelin 
--idare elemek uchundu demeli bu table'lar olsa yaxshi olar:
--RoomTypes, Rooms, Customers, Reservations, Payments(qonagin odenishleri), Spendings(qonagin xercleri). 
--Dahada genishlendire bilersiz, bu table'lari yaradib Relationlari duzgun shekilde qurub,
--Query'ler yazmaq(View,Procedure,Function,Trigger) her birine oz isteyinize uygun sample yazmaq.

CREATE DATABASE HOTEL1
USE HOTEL1


CREATE TABLE ROOMTYPES(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL,
CAPACITY INT NOT NULL,
DAILYPRICE MONEY)
INSERT INTO ROOMTYPES VALUES('FOR 1',1,50)
INSERT INTO ROOMTYPES VALUES('FOR 2',2,80)
INSERT INTO ROOMTYPES VALUES('VIP',2,150)

CREATE TABLE ROOMS(
ID INT PRIMARY KEY IDENTITY,
ROOMTYPEID INT REFERENCES ROOMTYPES(ID),
ROOMNO INT UNIQUE NOT NULL,
ISEMPTY BIT DEFAULT 1)

INSERT INTO ROOMS VALUES(2,258,1)
INSERT INTO ROOMS VALUES(1,147,0)
INSERT INTO ROOMS VALUES(3,369,1)


CREATE TABLE CUSTOMERS(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL,
SURNAME NVARCHAR(50) NOT NULL,
BIRTHDATE DATE NOT NULL,
PHONENUMBER INT NOT NULL,
PASSPORTCODE INT NOT NULL UNIQUE,
EMAIL NVARCHAR(255) NOT NULL UNIQUE,
ROOMID INT REFERENCES ROOMS(ID))


INSERT INTO CUSTOMERS
VALUES('Fidan','Mammadova','2002-09-04','0707570708',542445120,'f623@gmail.com',1)
INSERT INTO CUSTOMERS
VALUES('Jale','Mirzayeva','2002-09-01','0707570707',654154,'jaja@gmail.com',2)
INSERT INTO CUSTOMERS
VALUES('Rasul','Ismayilov','2002-07-28','0707570909',64163520,'eeesul@gmail.com',3)



CREATE TABLE RESERVATIONS(
ID INT PRIMARY KEY IDENTITY,
CUSTOMERID INT REFERENCES CUSTOMERS(ID),
ROOMID INT REFERENCES ROOMS(ID),
FIRSTDAY DATE NOT NULL,
ENDDAY DATE NOT NULL,
COUNTOFDAYS INT NOT NULL)

INSERT INTO RESERVATIONS 
VALUES(1,3,'2022-05-15','2022-05-20',DATEDIFF(DAY,'2022-05-15','2022-05-20'))
INSERT INTO RESERVATIONS 
VALUES(2,1,'2022-01-20','2022-01-22',DATEDIFF(DAY,'2022-01-20','2022-01-22'))
INSERT INTO RESERVATIONS 
VALUES(3,2,'2022-04-14','2022-04-15',DATEDIFF(DAY,'2022-04-14','2022-04-15'))


CREATE TABLE PAYMENTS(
ID INT PRIMARY KEY IDENTITY,
PAYMENTTYPE NVARCHAR(50),
PAYMENT MONEY,
CUSTOMERID INT REFERENCES CUSTOMERS(ID))

INSERT INTO PAYMENTS VALUES ('BY CASH',200,1)
INSERT INTO PAYMENTS VALUES ('BY CARD',100,2)


CREATE TABLE SPENDINGS(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL,
CUSTOMERID INT REFERENCES CUSTOMERS(ID),
AMOUNT MONEY)

INSERT INTO SPENDINGS VALUES ('SPA',1,150)
INSERT INTO SPENDINGS VALUES ('DINNER',2,60)
INSERT INTO SPENDINGS VALUES ('GYM',3,30)


----VIEW
CREATE VIEW VW_HOTEL
AS
SELECT CUSTOMERS.NAME+' '+SURNAME AS 'FULLNAME',ROOMTYPES.NAME,ROOMS.ROOMNO FROM CUSTOMERS 
JOIN ROOMS
ON ROOMS.ID=CUSTOMERS.ROOMID
JOIN ROOMTYPES
ON ROOMTYPES.ID=ROOMS.ROOMTYPEID


----PROCEDURE
CREATE PROCEDURE GETSPENDINGSOFCUSTOMERS @customid int
AS
SELECT CUSTOMERS.NAME+' '+CUSTOMERS.SURNAME AS 'FULLNAME',SPENDINGS.AMOUNT FROM CUSTOMERS
JOIN SPENDINGS
ON CUSTOMERID=CUSTOMERS.ID
WHERE @customid=CUSTOMERS.ID

EXEC GETSPENDINGSOFCUSTOMERS @customid=1

----FUNCTION
CREATE FUNCTION GETTYPEOFROOMS (@ROOMNO int)
RETURNS BIT
AS
BEGIN
     DECLARE @ISEMPTY BIT
     SELECT @ISEMPTY=ROOMS.ISEMPTY FROM ROOMS 
     WHERE  @ROOMNO=ROOMS.ROOMNO
	 RETURN @ISEMPTY
END

SELECT [DBO].[GETTYPEOFROOMS](147)

----TRIGGER
CREATE TRIGGER INSERTINGTRIGGER
ON CUSTOMERS
AFTER INSERT
AS
BEGIN
	SELECT * FROM CUSTOMERS
END



